name: forresto.jp
favicon: null
layout_spectrum: 0.50171
site_lang: ja
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006a9d'
    - '#f75256'
    - '#ffd66a'
    - '#ffffff'
    - '#718792'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
